# Jekyll configuration

name: DevonPeel.me
description: " Personal  Website  for  Devon  Peel.
Christ follower, Techie, Kansas State and KC Royals Fan"

# url is currently only used only for the RSS feed in feed.xml
url: https://devonpeel.me
# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: 'devonpeel.me'

# This can be '' to hide the Github nav button
github: 'dp3'

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: ''

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: ''
comments: true

permalink: /:year/:month/:title
paginate: 3

highlighter: rouge
markdown: kramdown
gems: ['jekyll-paginate']

exclude: ['README.md', 'LICENSE']
